config/routes.rb
Iou::Application.routes.draw do
  root :to => 'bills#new'

  resources :bills
  match '/bills/:id/billconfirmation' => 'bills#billconfirmation', :via => :post, :as => :billconfirmation

	resources :debts, :only => [:create, :new, :show]
	match '/payments/new', :to => 'debts#new'
  match '/debts/:id/paymentconfirmation' => 'debts#paymentconfirmation', :via => :post, :as => :paymentconfirmation

  resources :session, :only => [:create, :destroy, :new]
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"

  resources :users, :except => [:destroy, :index]
  match '/:id' => 'users#show', :as => :user
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	include ApplicationHelper, SessionHelper

	def new
		render :new
	end

	def create
		@user = User.find_by_email(params[:user][:email])

		if @user && @user.verify_password(params[:user][:password])
			login_user(@user)
			flash[:notice] = "Successfully logged in."
			redirect_to user_url(@user)
		else
			flash[:notice] = "Problem logging in. Please try again."
			render :new
		end
	end

	def destroy
		logout_user
		flash[:notice] = "Successful logout."
		redirect_to new_session_url
	end
end

app/helpers/session_helper.rb
module SessionHelper
	def logged_in?
		!!current_user
	end

	def login_user(user)
		token = SecureRandom.base64(16)
		user.session_token = token
		session[:session_token] = token
		user.save
	end

	def logout_user
		if current_user
			current_user[:session_token] = nil
			current_user.save
		end

		if session[:session_token]
			session[:session_token] = nil
		end
	end
end

app/views/session/new.html.erb
<h2>Login</h2>

<form id="login-form" action="<%= session_index_url %>" method="post">
	<input type="text" id="email" name="user[email]" placeholder="Email"/> <span id="login-email-errors" class="form-errors alert alert-danger"></span>
	<br>
	<input type="password" id="password" name="user[password]" placeholder="Password" /> <span id="login-password-errors" class="form-errors alert alert-danger"></span>
	<br>
	<input type="submit" class="btn btn-success" value="Login" />
</form>

<br>
<p>Don't have an account? <%= link_to "Create Account", new_user_url %></p>

<p><%= link_to "Back to Index", root_url %></p>