config/routes.rb
Iou::Application.routes.draw do
  root :to => 'bills#new'

  resources :bills
  match '/bills/:id/billconfirmation' => 'bills#billconfirmation', :via => :post, :as => :billconfirmation

	resources :debts, :only => [:create, :new, :show]
	match '/payments/new', :to => 'debts#new'
  match '/debts/:id/paymentconfirmation' => 'debts#paymentconfirmation', :via => :post, :as => :paymentconfirmation

  resources :session, :only => [:create, :destroy, :new]
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"

  resources :users, :except => [:destroy, :index]
  match '/:id' => 'users#show', :as => :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password

  validates :name, :email, :password, presence: :true, unless: :guest?
  validates :email, :uniqueness => { :case_sensitive => false }, allow_blank: :true
  validates :name, uniqueness: :true, allow_blank: :true

  has_many :bills

  has_many :debts,
    :foreign_key => "debtor_id"
    
  has_many :credits, 
    :class_name => "Debt",
    :foreign_key => "creditor_id"

  has_many :debtors,
    :through => :credits
    
  has_many :creditors, 
    :through => :debts
  
  has_many :invoices,
    :through => :credits,
    :source => :bill,
    :foreign_key => :creditor_id

	def password
    @password || self.password_digest
  end

  def password=(password)
  	@password = password
  	self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
  	BCrypt::Password.new(self.password_digest) == password
  end

  def to_param
    name
  end

  def self.new_guest
    new { |u| u.guest = true }
  end

  def move_to(user)
    bills.update_all(user_id: user.id)
    credits.update_all(creditor_id: user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper
	before_filter :require_login, :only => [:edit, :show]

	def new
		@user = User.new
		render :new
	end

	def create
		params[:user][:name] = params[:user][:name].downcase
		@user = User.new(params[:user])
		@user.guest = false

		if @user.save
			current_user.move_to(@user)
			flash[:notice] = "Account created. Please login."
			redirect_to new_session_url
		else
			flash[:notice] = "Unable to create account. Try again."
			render :new
		end
	end

	def edit
		@user = current_user
		render :edit
	end

	def update
	end

	def show
		@user = current_user
		@bills = @user.bills
		@payments = Debt.where(:creditor_id => @user.id, :is_a_payment => true)
		render :show
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Account Information</h1>

<form action="<%= users_url %>" method="post">
	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<input type="text" id="name" name="user[name]" value="<%= @user.name %>" placeholder="name">
	<br>
	<input type="text" id="email" name="user[email]" value="<%= @user.email %>" placeholder="email">
	<br>
	<input type="password" id="password" name="user[password]" placeholder="password">
	<br>
	<input type="submit" class="btn btn-success" value="Create Account">
	<input name="_method" type="hidden" value="put">
</form>

<p><%= link_to "Back to Index", root_url %></p>

app/views/users/new.html.erb
<h2>Create Account</h2>

<form id="new-account-form" action="<%= users_url %>" method="post">
	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<input type="text" id="name" name="user[name]" value="<%= @user.name %>" placeholder="name"> <span id="account-name-errors" class="form-errors alert alert-danger"></span>
	<br>
	<input type="text" id="email" name="user[email]" value="<%= @user.email %>" placeholder="email"> <span id="account-email-errors" class="form-errors alert alert-danger"></span>
	<br>
	<input type="password" id="password" name="user[password]" placeholder="password"> <span id="account-password-errors" class="form-errors alert alert-danger"></span>
	<br>
	<input type="submit" class="btn btn-success" value="Create Account">
</form>

<br>
Have an account already? 
<%= link_to "Login", login_url %>
<br>
<br>
<%= link_to "Back to Index", root_url %>

app/views/users/show.html.erb
<h2>Hi <%= @user.name %>!</h2>

<h3>Dashboard</h3>
<h3>Bills</h3>

<% if @bills.empty? %>
  <p>You have no bills.</p>
<% else %>
	<% @bills.each do |bill| %>
		<p>
			<b><%= bill.created_at.to_time.strftime('%B %e at %l:%M %p') %>:</b> Bill <%= bill.id %>
		  <%= link_to "#{ bill.name }", bill_url(bill) %> <%= link_to "Edit Bill #{bill.id}", edit_bill_url(bill), :class => "btn btn-warning" %> <button class="btn btn-primary">Mark as Paid</button>
	  </p>
	<% end %>
<% end %>

<h3>Payments</h3>
<% if @payments.empty? %>
	<p>You have no payments.</p>
<% else %>
	<% @payments.each do |payment| %>
		<p>
			<b><%= payment.created_at.to_time.strftime('%B %e at %l:%M %p') %>:</b>
		  <%= link_to "Payment #{ payment.id }", debt_url(payment) %>
	  </p>
	<% end %>
<% end %>

<h3>Find Friends</h3>
<textarea>Input friend email</textarea>
<button class="btn btn-primary">Send Friend Request</button>

<p><%= link_to "Return to Index Page", root_url %></p>
<% if logged_in? %>
	<p><%= button_to "Log out", session_url, :method => "delete", class: "btn btn-danger" %></p>
<% end %>