config/routes.rb
Iou::Application.routes.draw do
  root :to => 'bills#new'

  resources :bills
  match '/bills/:id/billconfirmation' => 'bills#billconfirmation', :via => :post, :as => :billconfirmation

	resources :debts, :only => [:create, :new, :show]
	match '/payments/new', :to => 'debts#new'
  match '/debts/:id/paymentconfirmation' => 'debts#paymentconfirmation', :via => :post, :as => :paymentconfirmation

  resources :session, :only => [:create, :destroy, :new]
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"

  resources :users, :except => [:destroy, :index]
  match '/:id' => 'users#show', :as => :user
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :description, :name, :amount, :id, :user

  validates :name, :amount, presence: :true

  belongs_to :user

  has_many :guests, dependent: :destroy

  has_many :debts, dependent: :destroy

  has_many :debtors, 
    :through => :debts, 
    :source => :debtor
    
  has_many :creditors, 
    :through => :debts, 
    :source => :creditor
    
  accepts_nested_attributes_for :debts, 
    :reject_if => :all_blank, 
    :allow_destroy => true

	def self.calculate(bill_id, bill_total, guests_params)
    guests_array = []
    
    guests_params.each do |guest|
      if guest.has_key?("amount_should_have_paid")
	      new_guest = Player.new(guest[:name], guest[:amount_paid].to_f, guest[:amount_should_have_paid].to_f)
	      Guest.create!(:name => guest[:name], :bill_id => bill_id, :amount_paid => guest[:amount_paid].to_f, :amount_should_have_paid => guest[:amount_should_have_paid].to_f)
      else
  	    amount_should_have_paid = bill_total / guests_params.length.to_f
        new_guest = Player.new(guest[:name], guest[:amount_paid].to_f, amount_should_have_paid)
	      Guest.create!(:name => guest[:name], :bill_id => bill_id, :amount_paid => guest[:amount_paid].to_f, :amount_should_have_paid => amount_should_have_paid)
	    end
      guests_array.push(new_guest)
    end
    
    guests_who_overpaid = []
    guests_who_underpaid = []

    guests_array.each do |guest|
      guests_who_overpaid.push(guest) if guest.bill_difference > 0
      guests_who_underpaid.push(guest) if guest.bill_difference < 0
    end
    
    debts_count = 0

    total_from_debtors = 0

    guests_who_underpaid.each do |guest|
      total_from_debtors += guest.amount_owes
    end

    guests_who_underpaid.each do |u_guest|
    
      guests_who_overpaid.each do |o_guest|
        owe_to_friend = u_guest.amount_owes * (o_guest.bill_difference/total_from_debtors.to_f)
        Debt.create!(:bill_id => bill_id, :debtor_name => u_guest.name, :creditor_name => o_guest.name, :amount => owe_to_friend)
        debts_count += 1
      end
		end
    
		"#{debts_count} debts created for this bill."
	end

  def self.correct_input(bill_total, guests_params)
    guests_payment = 0
    
    guests_params.each do |guest|
      guests_payment += guest[:amount_paid].to_f
    end
    
    guests_payment == bill_total
  end
end

class Player
  attr_accessor :name, :amount_paid, :amount_should_have_paid, :id
  
  def initialize(name, amount_paid, amount_should_have_paid)
    @name = name
    @amount_paid = amount_paid
    @amount_should_have_paid = amount_should_have_paid
  end
  
  def bill_difference
    @amount_paid - @amount_should_have_paid
  end
  
  def amount_owes
    @amount_should_have_paid - @amount_paid
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	include ApplicationHelper
	before_filter :require_login, :only => [:index]

	def index
		@bills = current_user.bills
		render :index
	end

	def new
		@user = current_user
		@bill = Bill.new
		render :new
	end

	def create
    bill_id = Bill.last.nil? ? 1 : Bill.last.id + 1
		@bill = Bill.new(:id => bill_id, :user => current_user, :name => params[:bill][:name], :description => params[:bill][:description], :amount => params[:bill][:amount])

		if @bill.valid?
			@bill.save

			print "### Bill Params"
			print params[:bill]

			params[:bill][:guests][0][:name] = current_user.name unless current_user.guest?

	    Bill.calculate(bill_id, params[:bill][:amount].to_i, params[:bill][:guests])

			respond_to do |format|
				format.json { render :json => {:error => "none", :message => "Bill id: #{@bill.id} successfully added."} }
				format.html { redirect_to bill_url(@bill) }
			end
		else
			flash[:notice] = "Error with your bill."
			render :new
		end
	end

	def edit
		@bill = Bill.find(params[:id])

		if current_user == @bill.user
			render :edit
		else
			flash[:notice] = "Login required to edit bill."
			redirect_to login_url
		end
	end

	def update

	end

	def show
		@bill = Bill.find(params[:id])
		@guests = @bill.guests
		@debts = @bill.debts

		if current_user == @bill.user
			render :show
		else
			flash[:notice] = "Login required to edit bill."
			redirect_to login_url
		end
	end

	def billconfirmation
		@bill = Bill.find(params[:id])
		email = params[:email]
    BillMailer.bill_confirmation(email, @bill).deliver  
    redirect_to root_url, notice: 'Bill confirmation sent.'
	end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/edit.html.erb
<h3>Edit Bill Page</h3>

app/views/bills/index.html.erb
<h1>Bills Index</h1>

<% @bills.each do |bill| %>
	<p>
		<b><%= bill.created_at.to_time.strftime('%B %e at %l:%M %p') %>:</b> Bill <%= bill.id %>
	  <%= link_to "#{ bill.name }", bill_url(bill) %> <%= button_to "Edit Bill #{bill.id}", edit_bill_url(bill), :class => "btn btn-warning" %>
  </p>
<% end %>

<p><%= link_to "Back to home page", root_url %></p>

app/views/bills/new.html.erb
<head>
</head>

<h2>IOU:<span class="lead"> An App for Group Expenses</span></h2>
<span class="lead">Use IOU right away. No account necessary!</span>
<br>
<br>
<h3>Add a Bill <span class="lead"> or <button class="btn btn-danger" data-toggle="modal" data-target="#payAFriend"> Pay A Friend </button></span></h3>

<form id="new-bill-form" action="<%= bills_url %>" method="post">
	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<input type="text" id="bill-name" name="bill[name]" value="<%= @bill.name %>" placeholder="Bill Name">
	<a href="#" data-placement="right" rel="tooltip" title="What was the bill for? For example: dinner, movies, rent"><button class="btn tooltip-info">?</button></a> <span id="bill-name-errors" class="form-errors alert alert-danger"></span>
	<br>

	<textarea id="bill-description" name="bill[description]" value="<%= @bill.description %>" placeholder="Bill Description (optional)" rows="2"></textarea>
	<a href="#" data-placement="right" rel="tooltip" title="Any notes about this bill? For example: 'Bill did not have an appetizer.' (This step is optional.)"><button class="btn tooltip-info">?</button></a>
	<br>

	<input type="number" id="bill-amount" name="bill[amount]" value="<%= @bill.amount %>" placeholder="Amount">
	<a href="#" data-placement="right" rel="tooltip" title="Enter the total bill amount."><button class="btn tooltip-info">?</button></a> <span id="bill-amount-errors" class="form-errors alert alert-danger"></span>
	<br>

	<br>
	<button class="btn btn-info" id="split-evenly">Split Evenly</button><a href="#" data-placement="right" rel="tooltip" title="Each person on this bill will owe the same amount."><button class="btn tooltip-info">?</button></a>
	<button class="btn btn-info" id="split-exact-amounts">Split by Exact Amounts</button><a href="#" data-placement="right" rel="tooltip" title="You will input what each person owes."><button class="btn tooltip-info">?</button></a>
	<br>

	<br>
	<div id="guests-on-bill"></div>
	<br>
</form>

<div id="form-submit-messages"></div>
<br>
<br>

<div class="modal fade" id="payAFriend" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Pay A Friend</h4>
      </div>
      <div class="modal-body">
      	<p><a href="/debts/new"><button class="btn btn-success"> Record a Cash Payment </button></a></p>
      	<p><a href="/"><button class="btn btn-danger"> Send Monday via PayPal </button></a></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/bills/show.html.erb
<h2>Bill #<%= @bill.id %> Details</h2>
<br>
Created by: <%= @bill.user.name.nil? ? "Guest User" : @bill.user.name %> on <%= @bill.created_at.to_time.strftime('%B %e at %l:%M %p') %>
<br>
Bill Name: <%= @bill.name %>
<br>
<% unless @bill.description.blank? %>
	Bill Description: <%= @bill.description %>
<% end %>
<br>
Bill Amount: $<%= sprintf( "%0.02f", @bill.amount) %>
<br>
<br>
<% @guests.each do |guest| %>
	<%= guest.name %> paid $<%= sprintf( "%0.02f", guest.amount_paid) %>. <%= guest.name %> should have paid $<%= sprintf( "%0.02f", guest.amount_should_have_paid) %>.
	<br>
<% end %>
<br>
<% @debts.each do |debt| %>
	<%= debt.debtor_name %> <%= debt.debtor_name == "You" ? "owe" : "owes" %> <%= debt.creditor_name == "You" ? "you" : debt.creditor_name %> $<%= sprintf( "%0.02f", debt.amount) %>.
	<br>
<% end %>
<br>
<br>
<div id="request-bill-confirmation">
	<input type="email" id="confirmation-email-address" placeholder="email@example.com"><button id="send-bill-confirmation" data-id=<%= @bill.id %> class="btn btn-primary"> Send Confirmation Email </button>
</div>
<br>
<br>
<div id="email-status">
</div>
<br>

<% if current_user.guest? %>
	<p><%= link_to "Create Account", new_user_url %> to save this bill.</p>
<% end %>

<p><%= link_to "Back to the index", root_url %></p>