config/routes.rb
Iou::Application.routes.draw do
  root :to => 'bills#new'

  resources :bills
  match '/bills/:id/billconfirmation' => 'bills#billconfirmation', :via => :post, :as => :billconfirmation

	resources :debts, :only => [:create, :new, :show]
	match '/payments/new', :to => 'debts#new'
  match '/debts/:id/paymentconfirmation' => 'debts#paymentconfirmation', :via => :post, :as => :paymentconfirmation

  resources :session, :only => [:create, :destroy, :new]
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"

  resources :users, :except => [:destroy, :index]
  match '/:id' => 'users#show', :as => :user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IOU: An App for Group Expenses</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="span3">
			<img src="http://www.clker.com/cliparts/1/7/5/6/13523340551621864223string-around-finger-never-dont-forget-md.png" />
			<br>
			<br>
		</div>
		<div class="span6">
			<% if flash[:notice] %>
				<br>
				<div class="alert">
				  <button type="button" class="close" data-dismiss="alert">&times;</button>
				  <strong>Message:</strong> <%= flash[:notice] %>
				</div>
			<% end %>

			<%= yield %>
		</div>
		<div class="span3">
			<% if current_user && current_user.guest? %>
				<%= link_to "Create Account", new_user_url %> | <%= link_to "Login", login_url %>
			<% else %>
				<span class="label label-success"> Logged in as </span> <%= current_user.email %>
				<br>
				<%= link_to "Profile", user_url(current_user) %>
				<br>
				<%= link_to "Logout", logout_url %>
			<% end %>
			<br>
			<h3>How to use:</h3>
			<ol>
				<li>Add a new bill.</li>
				<li>Select if you want to split evenly or split by exact amounts.</li>
				<li>List your friends who were part of the bill.</li>
				<li>IOU will calculate who owes what amount to whom.</li>
				<li>Email bill details to yourself and friends.</li>
			</ol>
			<br>
			<h4>Create a free account for more features:</h4>
			<ul>
				<li>Save and edit your bills.</li>
				<li>View payment history.</li>
				<li>Keep track of payments to friends.</li>
				<li>Use Paypal to pay friends.</li>
			</ul>
			<br>
			<div id="bio">
				<h4>About Belda</h4>
				<p>I built IOU with Ruby, Rails, jQuery/JavaScript, and Twitter Bootstrap. I love learning about technology and building things.</p>
				<p>View IOU on Github: <a href="https://github.com/hellobelda/IOU">www.github.com/hellobelda/iou</a></p>
				<p>Visit my Github: <a href="http://www.github.com/hellobelda">www.github.com/hellobelda</a></p>
				<p>Visit my LinkedIn: <a href="http://www.linkedin.com/in/beldachan">www.linkedin.com/in/beldachan</a></p>
				<p>Email me: beldac@gmail.com</p>
			</div>
		</div>
	</div>
</div>

<script>
if (typeof Iou === "undefined") {
	Iou = {};
}

<% if current_user.guest? %>
	Iou.currentUserId = "You";
<% else %>
	Iou.currentUserId = <%= current_user.id %>;
<% end %>
</script>
</body>
</html>